### ISSUE TITLE
jiwer.wer(outputs_true, outputs_pred, standardize=True)

### ISSUE THREAD

**Issue by hechengzhi985** [jitsi/jiwer#85]
Traceback (most recent call last):
File "main.py", line 222, in
main(0, args)
File "main.py", line 121, in main
model.fit(dataset_train,
File "EfficientConformer-master/models/model.py", line 344, in fit
raise e
File "EfficientConformer-master/models/model.py", line 303, in fit
wer, truths, preds, val_loss = self.evaluate(dataset, val_steps, verbose_val, eval_loss=True)
File "EfficientConformer-master/models/model.py", line 425, in evaluate
batch_wer = jiwer.wer(outputs_true, outputs_pred, standardize=True)
TypeError: wer() got an unexpected keyword argument 'standardize'

**Comment by nikvaessen** [comment]
The keyword `standardize` was deprecated since version 2.5.0. Eithet set `jiwer<=2.4`, or change the call:

```
import jiwer

jiwer.wer(
outputs_true, 
outputs_pred,
reference_transform=jiwer.wer_standardize, 
hypothesis_transform=jiwer.wer_standardize
)
```
